experimental = ["wrapper-scripts"]

[scripts.wrapper.valgrind]
command = ['valgrind', '-q', '--error-exitcode=1']

[[profile.valgrind.scripts]]
platform = 'cfg(target_os = "linux")'
run-wrapper = 'valgrind'
